- hosts: all
  gather_facts: True
  serial:
   - 1
   - 100%
  vars:
   - sftp_enabled: true
   - docker_group_members: [ubuntu]
  pre_tasks:
    - include_vars: group_vars/secrets.yml

    - name: Make sure wheel exists
      become: yes
      group:
        name: wheel
        state: present

    - name: Add ubuntu and root user to the wheel group
      become: yes
      user:
        name: "{{ item }}"
        groups: wheel
        append: yes
      with_items:
        - ubuntu
        - root

    - stat: path=/infinit
      register: infinit_exists

    - name: Create the infinit directory
      become: yes
      file:
        path: /infinit
        mode: 0755
        owner: root
        group: wheel
        state: directory
      when: infinit_exists.stat.exists == False

  roles:
    - { role: dev-sec.os-hardening, become: yes, tags: security }
    - { role: hutchic.infinit, become: yes, tags: infinit }

- hosts: vpc
  roles:
    - { role: grimmjow8.crashplan, become: yes }
