- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    ansible_python_interpreter: ".venv/bin/python"
    AWS_EC2_KEYPAIR_NAME: "mashape_shared"
    AWS_EC2_INSTANCE_SIZE: "t2.medium"
    AWS_VPC_SUBNET_ID: "subnet-aadf89cf"
    AWS_SECURITY_GROUP_ID: "sg-2de03f53"
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  tasks:
    - name: Create EC2 instance
      ec2:
        key_name: "{{ AWS_EC2_KEYPAIR_NAME }}"
        instance_type: "{{ AWS_EC2_INSTANCE_SIZE }}"
        image: "ami-d05e75b8"
        wait: true
        assign_public_ip: yes
        vpc_subnet_id: "{{ AWS_VPC_SUBNET_ID }}"
        group_id: "{{ AWS_SECURITY_GROUP_ID }}"
        exact_count: "1"
        region: "us-east-1"
        instance_tags:
          Name: "chutchinson"
        count_tag:
          Name: "chutchinson"
        volumes:
          - device_name: /dev/sda1
            volume_type: gp2
            volume_size: 100
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"

- hosts: tag_Name_chutchinson
  gather_facts: true
  vars:
    ansible_user: ubuntu
    security_ssh_password_authentication: yes
    security_sudoers_passwordless:
      - ubuntu
    sysctl_config:
      net.ipv4.ip_forward: 1
  pre_tasks:
    - name: Enable multiverse
      become: yes
      apt_repository: repo='{{item}}' update_cache=no
      with_items:
        - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
        - 'deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
        - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'
        - 'deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'

    - name: Upgrade via apt
      become: yes
      apt:
        upgrade: dist
        update_cache: yes

    - name: add key for ppa python repository
      become: yes
      apt_key: keyserver=keyserver.ubuntu.com id=DB82666C state=present

    - name: Add ppa python repository
      become: yes
      apt_repository: repo='deb http://ppa.launchpad.net/fkrull/deadsnakes-python2.7/ubuntu {{ ansible_distribution_release }} main' state=present update_cache=yes

    - name: ensure python2.7 tatest  is installed
      become: yes
      apt:
        pkg: python2.7
        state: latest
        install_recommends: no
  roles:
    - { role: vcabourdin.chrome, become: yes }
    - { role: dev-sec.os-hardening, become: yes }
    - { role: geerlingguy.docker, become: yes }
    - { role: geerlingguy.git, become: yes }
    - { role: geerlingguy.nfs, become: yes }
    - { role: geerlingguy.ntp, become: yes }
  post_tasks:
    - name: Add ubuntu user to docker group
      become: yes
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Install various packages
      become: yes
      apt:
        update_cache: yes
        name: "{{ item }}"
      with_items:
        - git
        - vim
        - wget
        - curl
        - build-essential
        - unzip
        - nmap
        - python-setuptools
        - python-pip
        - sshfs
        - firefox
        - screen
        - ubuntu-desktop
        - tar
        - gzip
        - ttf-ubuntu-font-family
