---
- name: Add Github apt signing key
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 23F3D4EA75716059
  become: yes

- name: Add Github Repository
  become: true
  apt_repository:
    repo: deb https://cli.github.com/packages focal main
    state: present

- name: Install gh-cli
  become: true
  apt:
    update_cache: true
    name: gh
    state: present
