---
- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    dest: "/usr/share/keyrings/docker-archive-keyring.gpg"
    mode: '0644'

- name: Add Docker repository
  ansible.builtin.lineinfile:
    path: "/etc/apt/sources.list.d/docker.list"
    line: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    create: yes
    state: present

- name: Install docker
  ansible.builtin.apt:
    update_cache: true
    name: docker-ce
    state: present

- name: Add user to docker group
  ansible.builtin.user:
    name: "ubuntu"
    groups: docker
    append: yes
