---
- name: Add 1Password GPG apt Key to system keyring
  ansible.builtin.shell:
    cmd: |
      curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg

- name: Add 1Password repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/1password.list
    line: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/{{ ansible_architecture }} stable main"
    create: yes

- name: Create debsig policy directory for 1Password
  ansible.builtin.file:
    path: /etc/debsig/policies/AC2D62742012EA22
    state: directory

- name: Add debsig policy for 1Password
  ansible.builtin.get_url:
    url: https://downloads.1password.com/linux/debian/debsig/1password.pol
    dest: /etc/debsig/policies/AC2D62742012EA22/1password.pol

- name: Create debsig keyring directory for 1Password
  ansible.builtin.file:
    path: /usr/share/debsig/keyrings/AC2D62742012EA22
    state: directory

- name: Add debsig keyring for 1Password
  ansible.builtin.shell:
    cmd: |
      curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg

- name: Update apt cache and install 1password-cli
  ansible.builtin.apt:
    update_cache: yes
    name: 1password-cli
    state: present
