- name: Download GitHub CLI GPG key
  ansible.builtin.get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /usr/share/keyrings/githubcli-archive-keyring.gpg
    mode: '0644'
    
- name: Add GitHub CLI Repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/github-cli.list
    line: "deb [signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages focal main"
    create: yes
    state: present

- name: Install GitHub CLI
  ansible.builtin.apt:
    update_cache: true
    name: gh
    state: present