---
- src: dev-sec.os-hardening
- src: vcabourdin.chrome
- src: geerlingguy.security
- src: geerlingguy.ntp
- src: geerlingguy.nfs
- src: jnv.unattended-upgrades
- src: badpacketsllc.aws_cli
- src: artis3n.tailscale
- src: arillso.sshd
- src: diodonfrost.terraform
