# Variables for use throughout the templates and taks.
user_id: 1004
group_id: 1004
TZ_TimeZone: America/Toronto
# Application Ports
plex_port: 32400
# Plex Docker Creation Variables
host_plex_config_path: /media/plexdb
host_media_tv_path: /media/tvshows
host_media_movies_path: /media/movies
host_media_anime_path: /media/anime
plex_transcode_path: /media/plexdb/transcode
plex_claim: claim-ipPmYWS5BT3WDN1Fk3vN
advertise_ip: http://192.168.0.44:32400
allowed_networks: 192.168.0.0/24
