- hosts: localhost
  connection: local
  vars:
    ansible_user: hutchic
    security_ssh_password_authentication: yes
    sysctl_config:
      net.ipv4.ip_forward: 1
  pre_tasks:
    - name: Enable multiverse
      become: yes
      apt_repository: repo='{{item}}' update_cache=no
      with_items:
        - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
        - 'deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
        - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'
        - 'deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'
        - 'deb http://download.videolan.org/pub/debian/stable/ /'
        - 'deb-src http://download.videolan.org/pub/debian/stable/ /'

    - name: Add videolan repository key
      become: yes
      apt_key:
        url: http://download.videolan.org/pub/debian/videolan-apt.asc
        state: present

    - name: Upgrade via apt
      become: yes
      apt:
        upgrade: dist
        update_cache: yes
  roles:
    - { role: plex }
    - { role: vcabourdin.chrome, become: yes }
    - { role: dev-sec.os-hardening, become: yes }
    - { role: geerlingguy.docker, become: yes }
    - { role: geerlingguy.nfs, become: yes }
    - { role: geerlingguy.ntp, become: yes }
    - { role: jnv.unattended-upgrades, become: yes }
  post_tasks:
    - name: Add hutchic user to docker group
      become: yes
      user:
        name: hutchic
        groups: docker
        append: yes

    - name: Install steam
      become: yes
      apt:
        deb: http://media.steampowered.com/client/installer/steam.deb

    - name: Create AACS directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /home/hutchic/.config
        - /home/hutchic/.config/aacs

    - name: Fetch the AACS config file
      get_url:
        url: http://vlc-bluray.whoknowsmy.name/files/KEYDB.cfg
        dest: /home/hutchic/.config/aacs/KEYDB.cfg

    - name: Add the makemkv repository
      become: yes
      apt_repository:
        repo: ppa:heyarje/makemkv-beta
        state: present

    - name: Install various packages
      become: yes
      apt:
        update_cache: yes
        name: "{{ item }}"
      with_items:
        - git
        - vim
        - vlc
        - wget
        - curl
        - build-essential
        - unzip
        - nmap
        - python-setuptools
        - python-pip
        - sshfs
        - firefox
        - screen
        - ubuntu-desktop
        - tar
        - gzip
        - ttf-ubuntu-font-family
        - libdvdcss2
        - ubuntu-restricted-extras
        - libdvd-pkg
        - libaacs0
        - libbluray-bdj
        - libbluray1
        - makemkv-bin
        - makemkv-oss
