- hosts: localhost
  connection: local
  vars:
    ansible_user: hutchic
    security_ssh_password_authentication: yes
    sysctl_config:
      net.ipv4.ip_forward: 1
  pre_tasks:
    - name: Enable multiverse
      become: yes
      apt_repository: repo='{{item}}' update_cache=no
      with_items:
        - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
        - 'deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
        - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'
        - 'deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'

    - name: Upgrade via apt
      become: yes
      apt:
        upgrade: dist
        update_cache: yes
  roles:
    - { role: plex }
    - { role: vcabourdin.chrome, become: yes }
    - { role: dev-sec.os-hardening, become: yes }
    - { role: geerlingguy.docker, become: yes }
    - { role: geerlingguy.nfs, become: yes }
    - { role: geerlingguy.ntp, become: yes }
    - { role: jnv.unattended-upgrades, become: yes }
  post_tasks:
    - name: Add hutchic user to docker group
      become: yes
      user:
        name: hutchic
        groups: docker
        append: yes

    - name: Install various packages
      become: yes
      apt:
        update_cache: yes
        name: "{{ item }}"
      with_items:
        - git
        - vim
        - wget
        - curl
        - build-essential
        - unzip
        - nmap
        - python-setuptools
        - python-pip
        - sshfs
        - firefox
        - screen
        - ubuntu-desktop
        - tar
        - gzip
        - ttf-ubuntu-font-family
