---
name: pip / python testing

on: pull_request # yamllint disable-line rule:truthy

jobs:
  validate-pip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.2
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5.0.0

    - run: pip install -r requirements.txt
