---
name: pip / python testing

on: pull_request # yamllint disable-line rule:truthy

jobs:
  validate-pip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.3
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v4.6.1

    - run: pip install -r requirements.txt
